name: Danger

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    name: Danger Check
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Danger Swift
        uses: danger/swift@3.0.0

      - name: Run Danger
        run: danger
